### ISSUE TITLE
Error CTC Loss - longer outputs than inputs

### ISSUE THREAD

**Issue by mohammedayub44** [bharatsubedi/OCR-Text-detection-and-Recognition-#3]
Hi,

I'm trying to run `train.py` using some synthetic images. I get an error after it runs for a while.  
My images are 600x450 size so I have changed the config accordingly like below -  
`CHAR_VECTOR = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-~<>'.:;^/|!?$%#@&*()[]{}_+=,\\\""`
`max_image_large_side = 600`
`max_text_size = 600`

**Stack Trace of the error:  **

```python

Parameters : 6129953
Epoch 000000, d_loss 0.0660, r_loss 77.3960, t_loss 0.8468,
Epoch 000010, d_loss 0.1337, r_loss 20.8005, t_loss 0.3485,
Epoch 000020, d_loss 0.0754, r_loss 17.9338, t_loss 0.2615,

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Not enough time for target transition sequence (required: 13, available: 11)7You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node CTCLoss}}]]
         [[CTCLoss/_219]]
  (1) Invalid argument: Not enough time for target transition sequence (required: 13, available: 11)7You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node CTCLoss}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 161, in <module>
    main()
  File "train.py", line 138, in main
    dl, rl, tl, _ = sess.run([d_loss, r_loss, total_loss, train_op], feed_dict=inp_dict)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Not enough time for target transition sequence (required: 13, available: 11)7You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[node CTCLoss (defined at /home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[CTCLoss/_219]]
  (1) Invalid argument: Not enough time for target transition sequence (required: 13, available: 11)7You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[node CTCLoss (defined at /home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'CTCLoss':
  File "train.py", line 161, in <module>
    main()
  File "train.py", line 78, in main
    input_training_masks, input_transcription, input_box_widths)
  File "train.py", line 35, in compute_loss
    recognition_loss = recognize_part.loss(recognition_logits, input_transcription, input_box_widths)
  File "/home/ubuntu/mayub/text_detection/FOTS_tf_efficientnet/Network/recognition.py", line 70, in loss
    loss = tf.compat.v1.nn.ctc_loss(targets, logits, seq_len)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/ops/ctc_ops.py", line 176, in ctc_loss
    ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_ctc_ops.py", line 336, in ctc_loss
    name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

```

Thanks in advance !

**Comment by mohammedayub44** [comment]
From this [post](https://stackoverflow.com/questions/66141239/invalid-argumentnot-enough-time-for-target-transition-sequence) , looks like something can be changed in the architecture last layer to make it work. 

For now, just added `ignore_longer_outputs_than_inputs=True` param in the `ctc_loss()` call in [recognition.py](https://github.com/bharatsubedi/FOTS_tf_efficientnet/blob/master/Network/recognition.py#L70)

Is there a better solution to support longer ground truth labels ?

**Comment by bharatsubedi** [comment]
@mohammedayub44 Thanks for your interest in my work. I never faced that type of issue during my development of this project. Could you please try to increase the max_text_size value and train again? I hope it will solve the problem.

**Comment by mohammedayub44** [comment]
@bharatsubedi  Thanks for the reply. My images are 600x450 maximum. Is it okay if max_text_size is greater than max image width or height. ?

**Comment by bharatsubedi** [comment]
@mohammedayub44 There is no link between text size and image size.

**Comment by mohammedayub44** [comment]
Thanks. It works fine if you add ignore param for now. Will open again if any downstream issues.
