### ISSUE TITLE
Testing Images throws InputTransformMatrix Shape Error

### ISSUE THREAD

**Issue by mohammedayub44** [bharatsubedi/OCR-Text-detection-and-Recognition-#4]
Hi,

I was successfully able to train on synthetic images. While testing with a trained checkpoint file I get an error on some of the images as show in Stack trace below. 

Looks like there are boxes detected, however `dataset.get_project_matrix_and_width()` returns no/invalid transform matrices. 
This is happening for only some test images. Not sure if this is because of my image or I'm missing something.

This is my test image: 
![desert_137_40](https://user-images.githubusercontent.com/7122670/118590582-aeb13000-b770-11eb-900e-067cf8a31489.jpg)

**Stack Trace of Error:**

```python

Traceback (most recent call last):
  File "test.py", line 226, in <module>
    main()
  File "test.py", line 151, in main
    input_box_widths: box_widths})
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1156, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'input_transform_matrix:0', which has shape '(?, 6)'
```

Appreciate any help. Thanks !

**Comment by mohammedayub44** [comment]
Figured it out. My model checkpoint was a bad one. Training further removes this issue.
